name: Java 20 CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Java 20
        uses: actions/setup-java@v3
        with:
          java-version: 20
          distribution: temurin

      - name: Set up cache for Gradle
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-java20-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-java20-

      - name: Build with Gradle
        run: ./gradlew build
        working-directory: Auto_Track

      - name: Run Tests
        run: ./gradlew test
        working-directory: Auto_Track

      - name: Publish Test Results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-results-java20
          path: Auto_Track/build/reports/tests/test
